import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, Plus } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useConnection } from "../../app/ConnectionContext";
import { Badge, Button, EmptyState, ErrorState, Panel, Skeleton } from "../../components/ui";
import { formatMoney, formatPercent } from "../../utils/format";

export function MerchantsPage() {
  const { client } = useConnection(); const qc = useQueryClient(); const query = useQuery({ queryKey: ["merchants"], queryFn: ({ signal }) => client.merchants(signal) }); const [open, setOpen] = useState(false);
  const mutation = useMutation({ mutationFn: (body: Record<string, unknown>) => client.createMerchant(body), onSuccess: async () => { setOpen(false); await qc.invalidateQueries({ queryKey: ["merchants"] }); } });
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); mutation.mutate({ merchant_id: f.get("merchant_id"), name: f.get("name"), vertical: f.get("vertical"), payment_provider: f.get("payment_provider") || null, razorpay_account_id: f.get("razorpay_account_id") || null, average_order_value: Number(f.get("average_order_value")), chargeback_history_count: 0, transaction_volume_30d_by_network: {} }); };
  return <><header className="page-heading"><div><p className="eyebrow">Workspace administration</p><h1>Merchants</h1><p>Provider mappings and observed dispute-ratio information.</p></div><Button onClick={() => setOpen(!open)}><Plus />Add merchant</Button></header>{open ? <Panel title="Create merchant"><form className="form-grid" onSubmit={submit}><label>Merchant ID<input name="merchant_id" required maxLength={100} /></label><label>Name<input name="name" required maxLength={200} /></label><label>Vertical<select name="vertical"><option value="ecommerce">E-commerce</option><option value="food_delivery">Food delivery</option><option value="quick_commerce">Quick commerce</option></select></label><label>Payment provider<select name="payment_provider"><option value="">None</option><option value="razorpay">Razorpay</option><option value="stripe">Stripe</option></select></label><label>Razorpay account ID<input name="razorpay_account_id" maxLength={100} /></label><label>Average order value<input name="average_order_value" type="number" min="0" step="0.01" defaultValue="0" /></label><div className="button-row"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" loading={mutation.isPending}>Create merchant</Button></div>{mutation.error ? <ErrorState error={mutation.error} /> : null}</form></Panel> : null}{query.isLoading ? <Skeleton lines={7} /> : query.error ? <ErrorState error={query.error} retry={() => void query.refetch()} /> : query.data?.length ? <div className="merchant-grid">{query.data.map(m => <Panel key={m.merchant_id}><div className="merchant-head"><span><Building2 /></span><div><h2>{m.name}</h2><small>{m.merchant_id}</small></div><Badge>{m.vertical.replaceAll("_", " ")}</Badge></div><dl className="detail-grid"><div><dt>Payment provider</dt><dd>{m.payment_provider || "Not configured"}</dd></div><div><dt>Razorpay account</dt><dd>{m.razorpay_account_id || "Not mapped"}</dd></div><div><dt>Average order value</dt><dd>{formatMoney(m.average_order_value, "INR")}</dd></div><div><dt>Prior chargebacks</dt><dd>{m.chargeback_history_count}</dd></div></dl>{Object.entries(m.merchant_dispute_ratio).length ? <div className="ratio-list">{Object.entries(m.merchant_dispute_ratio).map(([network, ratio]) => <span key={network}><strong>{network}</strong><Badge tone={ratio.status === "OK" ? "success" : ratio.status === "WARNING" ? "warning" : "neutral"}>{ratio.status}</Badge><small>{formatPercent(ratio.current_ratio_pct == null ? null : ratio.current_ratio_pct / 100)}</small></span>)}</div> : <p className="muted">No transaction-volume ratios configured.</p>}</Panel>)}</div> : <EmptyState title="No merchants configured">Create a merchant to establish an operational workspace.</EmptyState>}</>;
}
