import { useMutation } from "@tanstack/react-query";
import { Bot, Send, Square } from "lucide-react";
import { useRef, useState, type FormEvent } from "react";
import { ApiError } from "../../api/client";
import { useConnection } from "../../app/ConnectionContext";
import { Button, EmptyState, ErrorState, Panel } from "../../components/ui";

const prompts = ["Which cases have the nearest filing deadlines?", "Where is evidence collection degraded?", "Summarize the current recommendation mix."];
export function AssistantPage() {
  const { client } = useConnection(); const [question, setQuestion] = useState(""); const [caseId, setCaseId] = useState(""); const controller = useRef<AbortController | null>(null);
  const mutation = useMutation({ mutationFn: async () => { controller.current?.abort(); controller.current = new AbortController(); return client.askAssistant(question, caseId || undefined, controller.current.signal); } });
  const submit = (e: FormEvent) => { e.preventDefault(); if (question.trim()) mutation.mutate(); };
  const rate = mutation.error instanceof ApiError && mutation.error.status === 429 ? mutation.error.retryAfter : undefined;
  return <><header className="page-heading"><div><p className="eyebrow">Grounded case intelligence</p><h1>Guard AI</h1><p>Answers are generated from current ChargeGuard disputes and statistics, never from fabricated portfolio data.</p></div></header><div className="assistant-layout"><Panel className="assistant-panel"><div className="assistant-notice"><Bot />Responses are grounded in the authenticated workspace snapshot. Verify consequential actions in the case record.</div>{mutation.data ? <article className="assistant-answer" aria-live="polite"><span><Bot /></span><div><p>{mutation.data.answer}</p><small>Based on {mutation.data.based_on.dispute_count} disputes · stats snapshot {mutation.data.based_on.stats_snapshot ? "included" : "unavailable"}</small></div></article> : mutation.error ? <ErrorState error={mutation.error} retry={() => mutation.mutate()} /> : <EmptyState title="Ask about your portfolio">Choose a suggestion or enter an operational question.</EmptyState>}{rate ? <p className="warning-box">Rate limited. Try again in approximately {rate} seconds.</p> : null}<form className="assistant-form" onSubmit={submit}><label>Optional chargeback context<input value={caseId} onChange={(e) => setCaseId(e.target.value)} placeholder="cb_..." /></label><label>Your question<textarea value={question} onChange={(e) => setQuestion(e.target.value)} required maxLength={4000} /></label><div className="button-row">{mutation.isPending ? <Button type="button" variant="secondary" onClick={() => controller.current?.abort()}><Square />Cancel</Button> : null}<Button type="submit" loading={mutation.isPending}><Send />Ask Guard AI</Button></div></form></Panel><Panel title="Suggested questions"><div className="suggestions">{prompts.map(prompt => <button key={prompt} onClick={() => setQuestion(prompt)}>{prompt}</button>)}</div></Panel></div></>;
}
