import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FlaskConical } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useConnection } from "../../app/ConnectionContext";
import { Badge, Button, EmptyState, ErrorState, Panel, Skeleton } from "../../components/ui";
import { formatDate, formatMoney } from "../../utils/format";

export function SimulatorPage() {
  const { client } = useConnection(); const qc = useQueryClient(); const merchants = useQuery({ queryKey: ["merchants"], queryFn: ({ signal }) => client.merchants(signal) }); const simulations = useQuery({ queryKey: ["simulator"], queryFn: ({ signal }) => client.simulatorDisputes(signal), retry: false }); const [notice, setNotice] = useState("");
  const create = useMutation({ mutationFn: (body: Record<string, unknown>) => client.createSimulation(body), onSuccess: async data => { setNotice(`Test dispute ${data.dispute_id} was created and delivered locally.`); await Promise.all([qc.invalidateQueries({ queryKey: ["simulator"] }), qc.invalidateQueries({ queryKey: ["disputes"] })]); } });
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); create.mutate({ merchant_id: f.get("merchant_id"), payment_id: f.get("payment_id"), order_id: f.get("order_id"), payment_amount_paise: Number(f.get("payment_amount_paise")), dispute_amount_paise: Number(f.get("dispute_amount_paise")), currency: f.get("currency"), method: "card", card_network: f.get("card_network"), razorpay_reason_code: f.get("razorpay_reason_code"), respond_within_hours: 72 }); };
  return <><header className="page-heading"><div><p className="eyebrow">Development-only tooling</p><h1>Razorpay simulator</h1><p>Generates signed, loopback-only test events. It never requires or contacts real Razorpay credentials.</p></div><Badge tone="warning">TEST DATA</Badge></header><div className="sim-grid"><Panel title="Create a test dispute"><form className="form-grid" onSubmit={submit}><label>Merchant<select name="merchant_id" required><option value="">Select merchant</option>{merchants.data?.filter(m => m.payment_provider === "razorpay" && m.razorpay_account_id).map(m => <option key={m.merchant_id} value={m.merchant_id}>{m.name}</option>)}</select></label><label>Payment ID<input name="payment_id" required defaultValue="pay_SIM_test" /></label><label>Order ID<input name="order_id" required defaultValue="order_SIM_test" /></label><label>Payment amount (paise)<input name="payment_amount_paise" type="number" min="1" required defaultValue="150000" /></label><label>Dispute amount (paise)<input name="dispute_amount_paise" type="number" min="1" required defaultValue="120000" /></label><label>Currency<input name="currency" required minLength={3} maxLength={3} defaultValue="INR" /></label><label>Card network<select name="card_network"><option>VISA</option><option>MASTERCARD</option><option>RUPAY</option><option>AMEX</option></select></label><label>Razorpay reason code<input name="razorpay_reason_code" required defaultValue="fraudulent" /></label><Button type="submit" loading={create.isPending}><FlaskConical />Create test dispute</Button>{create.error ? <ErrorState error={create.error} /> : null}{notice ? <p className="success-box" role="status">{notice}</p> : null}</form></Panel><Panel title="Test records">{simulations.isLoading ? <Skeleton lines={5} /> : simulations.error ? <ErrorState error={simulations.error} /> : simulations.data?.length ? <div className="event-list">{simulations.data.map(s => <article key={s.dispute_id}><span><strong>{s.dispute_id}</strong><small>{s.order_id} · {s.payment_id}</small></span><Badge tone="warning">TEST · {s.state}</Badge><b>{formatMoney(s.dispute_amount_paise / 100, s.currency)}</b><small>Created {formatDate(s.created_at)}</small></article>)}</div> : <EmptyState title="No test disputes">Create one using a mapped Razorpay test merchant.</EmptyState>}</Panel></div></>;
}
